server:
  port: 8087

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3308/lottery?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml


# 多数据源的路由配置
mini-db-router:
  jdbc:
    datasource:
      dbCount: 2
      tbCount: 4
      default: db00
      routerKey: uId
      list: db01,db02
      db00:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3308/lottery?useUnicode=true
        username: root
        password: 123
      db01:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3308/lottery_01?useUnicode=true
        username: root
        password: 123
      db02:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3308/lottery_02?useUnicode=true
        username: root
        password: 123


# dubbo
dubbo:
  application:
    name: lottery
    version: 1.0.0
  registry:
    address: N/A #直连模式
#    address: multicast://10.192.24.196:1234
#     address: multicast://127.0.0.1:1234??unicast=false

  protocol:
    name: dubbo
    port: 20885
#    host: 10.192.24.196
  scan:
    base-packages: org.example.rpc

